### PR TITLE
Making a basic e-commerce website

### PR DESCRIPTION
**Pull request by yashthipsay**
--Fork and clone the repository
 
 Make a PR with an explanation:
 -- An image of the blog - 
image

 -- What all is explained in it- This is a complete step-by-step process to create an e-commerce website, with code and no-code explanations. The blog also has specific tasks for readers to research and code. It uses the latest tech stack and also teaches what specific code is used for. It teaches full-stack frameworks like creating a database, writing queries, creating frontend, and creating REST API provided by the database. 

 -- Any images used in the blog, show them as well - 
image
image
image
image

### CODE REVIEW

**Comment by yashthipsay** [comment]
Hi @EzpieCo. I have added the blog file. Please merge it

**Review by EzpieCo — APPROVED** [review]
Though there was still the problem with the naming, as the permalink in the frontmatter should be the same name as the file name, but don't worry you have done your part and now it's our to fix the problems, so don't worry we will accept your PR.

**Comment by yashthipsay** [comment]
Thank you @EzpieCo!

**Comment by EzpieCo** [comment]
Your welcome! Happy hacktoberfest @yashthipsay! You can always come here and add your ideas we are always open for contribution 😄

**Comment by yashthipsay** [comment]
Hi @EzpieCo. I can see your merged issue on my hacktoberfest profile. But I can not see another issue that was merged. Do you know why there is this bug?

**Comment by EzpieCo** [comment]
It might be something with hacktoberfest, which I can't really help with, it's on their hands.

**Comment by EzpieCo** [comment]
@yashthipsay we have one more issue which i guess you can work on, check it here #13. It's about angular components.

**Comment by yashthipsay** [comment]
> @yashthipsay we have one more issue which i guess you can work on, check it here #13. It's about angular components.

Sure! I will do this as my next blog

**Comment by EzpieCo** [comment]
Also, if you wish you can join our discord server too, here's the link: https://discord.gg/uxarDQph

**Comment by yashthipsay** [comment]
> Also, if you wish you can join our discord server too, here's the link: https://discord.gg/uxarDQph

Sure

**Pull request merged**
